# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Paksa APK Signature v2 (wajib untuk Android 11 di MIUI/ColorOS/RealmeUI)
android.enableV2SigningScheme=true

# Nonaktifkan build features yang tidak dipakai
android.defaults.buildfeatures.buildconfig=false
android.nonTransitiveRClass=true
